version: '3.9'

services: 
  frontend:
    restart: unless-stopped
    build: frontend/game-news-frontend
    ports:
      - "5173:5173"
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  article:
    restart: unless-stopped
    build:
      context: backend/GameNews.Articles
      dockerfile: src/GameNews.Articles.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    ports:
      - "8050:80"

  db:
    restart: unless-stopped
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: article
    volumes:
      - db:/var/lib/postgresql/data

volumes: 
  db:
    driver: local