version: '3.9'

services: 
  frontend:
    restart: unless-stopped
    build: frontend/game-news-frontend
    ports:
      - "5173:5173"

  api:
    restart: unless-stopped
    build:
      context: backend/GameNews.Articles
      dockerfile: src/GameNews.Articles.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '8080:80'
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: article
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "15432:5432"

volumes: 
  db:
    driver: local