version: '3.9'

include:
  - frontend/game-news-frontend/docker-compose.yaml
  - backend/GameNews.OAuth/docker-compose.yaml
  - backend/GameNews.MediaStorage/docker-compose.yaml
  - backend/GameNews.Articles/docker-compose.yaml

services:   
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"