version: '3.9'

services: 
  frontend:
    build: frontend/game-news-frontend
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  article:
    build:
      context: backend/GameNews.Articles
      dockerfile: src/GameNews.Articles.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: article
    volumes:
      - db:/var/lib/postgresql/data
  
  auth:
    build:
      context: backend/GameNews.OAuth
      dockerfile: src/GameNews.OAuth.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DiscordApiOptions__ClientId=
      - DiscordApiOptions__ClientSecret=

volumes: 
  db:
    driver: local