@host="http:\\localhost:8080"

### upload

POST {{host}}/api/storage/media-files/dcd6e879-48e4-478e-b60d-a1cd441f45f4

Authorization: Bearer hDF4WijRAwr8sNBktTZpcdY1y3cxwI

> files/Shablon.png

### update meta

PUT /api/storage/media-file/{articleId:guid}/{id:guid}/meta

Authorization: Bearer {token}

{
    "alt": "описания изображения "
}

### get

GET {{host}}/api/storage/media-files/dcd6e879-48e4-478e-b60d-a1cd441f45f4/752f8618-3992-4ae9-9320-cb6bbaffabd8

### get meta

GET {{host}}/api/storage/media-files/{articleId:guid}/{id:guid}/meta

### get all meta by article

GET {{host}}/api/storage/media-files/{articleId:guid}/meta

### delete

DELETE {{host}}/api/storage/media-file/{articleId:guid}/{id:guid}

### delete all by article

DELETE {{host}}/api/storage/media-file/{articleId:guid}
