version: '3.9'

services: 
  articles:
    build:
      context: .
      dockerfile: src/GameNews.Articles.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '8080:80'